# debug模式，后台看到插件运行状况
Debug: false
# 技能描述的二级预览中间分隔符
# 分隔符前后将保证格式一致性
DescriptionSplit: "&0→"
# 注册技能组类型，只能切换以下技能组或其他插件注册的
Group:
  - "爆发"
  - "持久"
# ！修改后需要重启
# 多服同步缓存：redis/broker/disable
CacheManager: "disable"
# 多少Tick自然恢复法力值一次
ManaRegainTick: 20
# 多少Tick自然恢复精力值一次
SpiritRegainTick: 20
# 是否取消饱食度
DisableHunger: false
# 是否取消僵尸因为太阳光导致着火
DisabledCombust: false
# 释放技能时是否静默
Silence: false
# 是否需要同步原版经验
SyncExperience: true
# 是否取消因为速度改变产生的FOV角变化
OffSpeedFovChange: true
UI:
  # ！修改后需要重启
  # bukkit/germplugin/dragoncore
  use: "bukkit"
# 持久存储数据库
Database:
  # ！修改后需要重启
  # SQLLITE,MYSQL,H2
  use: SQLLITE
  # sqllite/h2 专用设置文件存储位置
  # {0} 为插件文件夹位置
  path: "{0}"
  sql:
    password: 123456
    database: orryx
    port: 3306
    host: 127.0.0.1
    user: root
# 生成飞书Wiki文档 不懂不用管
LarkSuite:
  AppId: ""
  AppSecret: ""
  ParentWikiToken: ""
  SpaceId: ""
# AI接入
OpenAI:
  ApiKey: ""
  BaseUrl: ""
# KTS 脚本配置
Kts:
  # 自定义 JDK 目录（可选）
  # 如果不设置或为空，将使用当前 Java 运行时的 JDK
  Jdk: "/home/zhibei/zulu8.84.0.15-ca-jdk8.0.442-linux_x64"