# debug模式，后台看到插件运行状况
Debug: false
# 技能描述的二级预览中间分隔符
# 分隔符前后将保证格式一致性
DescriptionSplit: "&0→"
# 注册技能组类型，只能切换以下技能组或其他插件注册的
Group:
  - "爆发"
  - "持久"
# ！修改后需要重启
# 多服同步缓存：redis/broker/disable
CacheManager: "disable"
# 多少Tick自然恢复法力值一次
ManaReginTick: 20
# 是否取消饱食度
DisableHunger: false
# 释放技能时是否静默
Silence: false
UI:
  # ！修改后需要重启
  # bukkit/germplugin/dragoncore
  use: "bukkit"
# 持久存储数据库
Database:
  # ！修改后需要重启
  # SQLLITE,MYSQL
  use: SQLLITE
  sql:
    password: 123456
    database: orryx
    port: 3306
    host: 127.0.0.1
    user: root
# 生成飞书Wiki文档 不懂不用管
LarkSuite:
  AppId: ""
  AppSecret: ""
  ParentWikiToken: ""
  SpaceId: ""
# AI接入
OpenAI:
  ApiKey: ""
  BaseUrl: ""